// We are overriding the autogenerated client to point to *your* Supabase project.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Get these from: Supabase Dashboard → Project Settings → API
const SUPABASE_URL = "https://qixhtzxbnovfzqiammjp.supabase.co";
const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpeGh0enhibm92ZnpxaWFtbWpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5Mjc3NTIsImV4cCI6MjA3NTUwMzc1Mn0.BYkWfRChIg6Yur6jk4jr7iocKuBWHGLr3N2urE1B_ZA"; // aka “publishable” key

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
